tap "buo/cask-upgrade"
tap "caskroom/cask"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "homebrew/bundle"
tap "homebrew/core"
brew "ccat"
brew "coreutils"
brew "dark-mode"
brew "docker-machine-driver-xhyve"
brew "envchain"
brew "exa"
brew "findutils"
brew "fzf"
brew "go"
brew "htop"
brew "hub"
brew "python3"
brew "ipython"
brew "jq"
brew "libgit2"
brew "python"
brew "libmagic"
brew "m-cli"
brew "mas"
brew "minisign"
brew "mitmproxy"
brew "moreutils"
brew "mtr"
brew "neovim"
brew "node"
brew "reattach-to-user-namespace"
brew "ruby"
brew "socat"
brew "stow"
brew "terminal-notifier"
brew "the_silver_searcher"
brew "tmux"
brew "watch"
brew "z"
brew "zplug", args: ["with-zsh"]
brew "zsh"
cask "appcleaner"
cask "charles"
cask "flash-player"
cask "font-source-code-pro-for-powerline"
cask "gitter"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-play-music-desktop-player"
cask "gpgtools"
cask "iina"
cask "minikube"
cask "music-manager"
cask "paw"
cask "safari-technology-preview"
cask "skype"
cask "slack"
cask "spectacle"
cask "vlc"
cask "wwdc"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Server", id: 883878097

unless `hostname`.strip == 'gkambp'
  cask "beatport-pro"
  cask "private-internet-access"
  cask "transmission"
  cask "webtorrent"
end
